전형 구분 페이지 UI 제작 + Redux 코드 구축
EntryDSM/Russianblue pull request #5
Opened 2021-05-30 13:35 UTC by hyejun0608

# 전형 구분 페이지 UI 제작 + Redux 코드 구축

### 요약
전형 구분 페이지 마크업과 리덕스 코드를 완성하였습니다. 컴포넌트와 리덕스 연동도 하였습니다..

2021-05-30 13:43 UTC, sema0710 requested changes

2021-05-30 13:43 UTC, sema0710 commented on src/components/SelectType/Select/MonthSelect.tsx
> +            })}
컴포넌트 렌더링 시에 배열 생성하는것 매우 비효율적 이라고 생각해요.
배열을 useRef로 만들고 map 돌리는 코드를 함수로 빼서 처리하는게 어떨지요

2021-05-30 13:43 UTC, sema0710 commented on src/components/SelectType/Select/MonthSelect.tsx
> +  };
이 코드들 ~Select인 파일마다 다 사용하는거 같은데 HOC 사용해서 재사용하는건 어때요?

2021-05-30 13:43 UTC, sema0710 commented on src/components/SelectType/Select/TypeSelect.tsx
> +      <S.SelectContent width={135}>
이 부분도 중복인거같은데 HOC 처리할 때 같이 해버려요~

2021-05-30 13:43 UTC, sema0710 commented on src/components/SelectType/SelectLine.tsx
> +  const [isToBe, setIsToBe] = useState(false);
뭔 state인지 모르겠어요 네이밍 수정 부탁해요

2021-05-30 13:43 UTC, sema0710 commented on src/components/SelectType/SelectType.tsx
> +      <Pagination nowPage={[true, false, false, false, false]} />
? 뭐하는 컴포넌트에요?

2021-05-30 13:43 UTC, sema0710 commented on src/components/SelectType/column/ChooseGraduationDate.tsx
> +      <MonthSelect graduation_month={graduation_month} setGraduationMonth={setGraduationMonth} />
왜 카멜 케이스에요? 통일 해주세요

2021-05-30 14:46 UTC, woochanleee requested changes
잘했어요!

2021-05-30 14:46 UTC, woochanleee commented on src/components/SelectType/Select/MonthSelect.tsx
> +  setGraduationMonth: (payload: number) => void;
변수명 컨벤션 통일

2021-05-30 14:46 UTC, woochanleee commented on src/components/SelectType/Select/MonthSelect.tsx
> +  const [active, setActive] = useState(1);
보니까 active state를 1, 2 로 관리하는 이유는?
boolean값으로 해결 가능한가 고려

2021-05-30 14:46 UTC, woochanleee commented on src/components/SelectType/style/index.ts
> +    background-color: ${disabled === 3 ? '#f1f1f1' : '#ffffff'};
disabled props에 src/components/SelectType/Select/MonthSelect.tsx 에서 active state 사용하는데
active는 1 | 2 의 값인데 3이랑 0 은 어떻게 쓰이는건가요?

2021-05-30 14:46 UTC, woochanleee commented on src/components/SelectType/Select/MonthSelect.tsx
> +            })}
1월부터 12월까지 컴포넌트 map 돌리는 것 같은데 Array(12)로 하기보단
"1~12월까지의 리스트이다~" 라는 의미로 변수를 하나 지어서 
```js
const 1월부터12월 = [...Array(12)].map((_ , i) => i + 1);
return 1월부터12월.map(month => <p>{monthh}</p>);
```
리렌더링 될때마다 map 계속 실행되니까 메모이제이션 적용하기

2021-05-30 14:46 UTC, woochanleee commented on src/components/SelectType/Select/TypeSelect.tsx
> +        {disabled === 2 && <img src={dropdown_active} />}
0, 1, 2 로 조건문 처리하는건 너무 가독성 떨어지는 듯,
'disabled' | 'normal' | 'enabled' 타입으로 가져가서 사용하고
리턴 문 안에서 30, 31, 32 줄 코드 처럼 하기보단 따로 빼서 하나의 jsx만 렌더링하게 하는건 어떰?
const dropDown = useMemo(() => {
  if (disabled === 'disabled') return <img src={disabled} />
  else if (disabled === 'normal') return <img src={normal} />
}, [disabled])

return (
  {dropDown}
);

2021-05-30 14:46 UTC, woochanleee commented on src/components/SelectType/column/ChooseGraduation.tsx
> +            <S.CheckCircle onClick={onCheckBtnClick} data-id={data.id}>
index같은 1, 2, 3 사용하기보단 명확한 key값을 사용해주세요.
위에서 스위치 케이스 같은 경우에도 더 가독성이 좋을 것 같네요.

2021-05-30 14:46 UTC, woochanleee commented on src/components/SelectType/column/ChooseRegion.tsx
> +            <S.CheckCircle onClick={onCheckBtnClick} data-id={data.id}>
위와 동일

2021-05-30 14:46 UTC, woochanleee commented on src/components/SelectType/column/ChooseRemark.tsx
> +            <S.CheckCircle onClick={onCheckBtnClick} data-id={data.id}>
동일도옹오옹일

2021-05-30 14:46 UTC, woochanleee commented on src/components/SelectType/column/ChooseType.tsx
> +  };
얘도 도오오옹

2021-05-30 14:46 UTC, woochanleee commented on src/containers/selectType/SelectTypeContainer.tsx
> +
스토어에서 가져오는 훅을 컨테이너에서 써서 props로 넘겨준다?
의미가 있나 싶음. 괜히 interface 작성해야하는 코드량만 늘어나는게 아닌가.

@sema0710 이거 어떻게 생각함?

2021-05-30 14:46 UTC, woochanleee commented on src/modules/redux/reducer/selectType/index.ts
> +    case TYPE: {
case : 하고 중괄호 안써도 되는데 이건 하고싶은대로 하슈

2021-05-30 14:47 UTC, sema0710 commented on src/components/SelectType/Select/MonthSelect.tsx
> +  setGraduationMonth: (payload: number) => void;
나이스

2021-05-30 14:49 UTC, sema0710 commented on src/containers/selectType/SelectTypeContainer.tsx
> +
에...뭐 제가 저렇게 하라고 했는데, 컴포넌트 재사용성 증진을 위해서 저렇게 하는게 맞다고 생각해요.
근데 이건 사람 바이 사람이라고 생각함.
코드가 늘어나서 힘들다고 생각할 수 있는데, 저렇게 컨테이너로 감싸서 하면 컴포넌트는 redux에 의존하지 않기 때문에 컴포넌트를 다른곳에서 재활용 할 수 있다는 장점이 있습니당. 언제든 확장할 수 있게요.
코드 수 느는건 팩트~

2021-05-30 14:51 UTC, sema0710 commented on src/modules/redux/reducer/selectType/index.ts
> +    case TYPE: {
코드 폭력 멈춰!

2021-05-30 14:51 UTC, sema0710 commented on src/modules/redux/reducer/selectType/index.ts
> +    case TYPE: {
내가 하긴 했지만

2021-05-30 14:55 UTC, woochanleee commented on src/containers/selectType/SelectTypeContainer.tsx
> +
아 그런 의도로? ㅇㅎ

2021-05-31 10:04 UTC, hyejun0608 commented on src/components/SelectType/SelectType.tsx
> +      <Pagination nowPage={[true, false, false, false, false]} />
아래에 동그라미 여러개있고 이전 다음 버튼 있는 컴포넌트에요......

2021-06-01 07:46 UTC, sema0710 approved these changes

2021-06-01 07:48 UTC, woochanleee approved these changes
re request를 눌러야 메일이 옵니다!!!

2021-06-01 07:52 UTC, merged